# Generated by Django 3.1.3 on 2020-12-17 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, help_text="Amount of € spent.", max_digits=10)),
                ("comment", models.TextField(blank=True, help_text="Additional notes...", null=True)),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="data/images/")),
                (
                    "expense",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.expense"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("comment", models.TextField(blank=True, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "country",
                    models.CharField(choices=[("LT", "Lithuania"), ("DE", "Germany")], default="LT", max_length=2),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="location",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.location"),
        ),
        migrations.AddField(
            model_name="expense",
            name="owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.payment"),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document", models.FileField(upload_to="data/documents/")),
                (
                    "expense",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.expense"),
                ),
            ],
        ),
    ]
