# Generated by Django 3.1.3 on 2020-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="expense",
        ),
        migrations.AddField(
            model_name="expense",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="data/documents/"),
        ),
        migrations.AddField(
            model_name="expense",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="data/images/"),
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
    ]
