# Generated by Django 3.1.3 on 2020-12-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_auto_20201217_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="location",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.location"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.payment"),
        ),
    ]
