# Generated by Django 3.1.3 on 2020-12-17 20:21

from django.db import migrations, models

import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_auto_20201217_2005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to=expenses.models.UploadToPathAndRename("data/documents/")
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=expenses.models.UploadToPathAndRename("data/images")
            ),
        ),
    ]
