# Generated by Django 3.1.3 on 2020-12-17 21:25

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20201217_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PHYSICAL', 'Physical')], default='PHYSICAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=expenses.models.UploadToPathAndRename('documents/')),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=expenses.models.UploadToPathAndRename('images/')),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
